### ISSUE TITLE
How should I compile the component 'profile-api'?

### ISSUE THREAD

**Issue by Ahidada** [fermyon/code-things#25]
I ran the command 'cargo build' in api/profile, and then the dependency 'spin-sdk' was not found

`% cargo build
error: no matching package named `spin-sdk` found
location searched: https://github.com/fermyon/spin?tag=v1.0.0#df99be23
required by package ’profile-api v0.1.0 (/Users/zhang/EdgeSync/Code/code-things/api/profile)‘`

Is it not possible to compile spin-sdk on top of macos_x86?

```
note: Undefined symbols for architecture x86_64:
            "_outbound-pg_execute", referenced from:
                spin_sdk::pg::outbound_pg::execute::h549ce941af2fcae7 in libspin_sdk-69d1de8d91ccc8d7.rlib(spin_sdk-69d1de8d91ccc8d7.spin_sdk.d0efae5e-cgu.8.rcgu.o)
            "_outbound-pg_query", referenced from:
                spin_sdk::pg::outbound_pg::query::h441e7bfc89690c70 in libspin_sdk-69d1de8d91ccc8d7.rlib(spin_sdk-69d1de8d91ccc8d7.spin_sdk.d0efae5e-cgu.8.rcgu.o)
            "_spin-config_get-config", referenced from:
                spin_sdk::config::spin_config::get_config::h3b773e34149c50a6 in libspin_sdk-69d1de8d91ccc8d7.rlib(spin_sdk-69d1de8d91ccc8d7.spin_sdk.d0efae5e-cgu.6.rcgu.o)
            "_wasi-outbound-http_request", referenced from:
                spin_sdk::outbound_http::wasi_outbound_http::request::h670f0bb86de2f30b in libspin_sdk-69d1de8d91ccc8d7.rlib(spin_sdk-69d1de8d91ccc8d7.spin_sdk.d0efae5e-cgu.14.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          
error: could not compile `profile-api` due to previous error
```

**Comment by jpflueger** [comment]
Hello @Ahidada! Sorry for the delay, you're the first person that isn't me who has filed an issue on this repo :)

To build just the `api/profile` project you can either run `spin build` from the repository's root directory if you have the Spin CLI installed (probably required if you actually want to run the application) or you can run `cargo build --target wasm32-wasi --release`. The Spin SDK is specifically meant to compile to WebAssembly so the having the `--target wasm32-wasi` argument is a requirement for using the Spin SDK. Let me know if that solves your problem!

**Comment by Ahidada** [comment]
Thanks for your answer, I pulled the latest code and now I can spin build and spin deploy, it worked.

**Comment by jpflueger** [comment]
Awesome, thanks for filing a ticket and feel free to submit a PR if you have any changes or additions!
